# Generated by Django 4.2 on 2023-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vots',
            new_name='votes',
        ),
    ]
