# Generated by Django 4.2 on 2023-05-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_rename_vots_choice_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_one',
        ),
    ]
