# Generated by Django 4.2 on 2023-05-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_rename_question_one_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='questionone',
        ),
    ]
